name: gif test
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0.36431734007783234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.0019203023985028267
  saturation: 0.8125
  rhythmicContrast: 0.35878547956235707
purpose: []
